Repository jdwilkin4/fcc-forum-clone, pull requests merged in 2022-10, with the labels that each got.

#33 docs: changed structure of the README
  README.md
Labels: documentation

#29 docs: Added contributing guide
  CONTRIBUTING.md
Labels: documentation

#37 chore: add a table of contents to CONTRIBUTING file
  CONTRIBUTING.md
Labels: chore

#35 table-headers-and-style-added
  index.html
  styles.css
Labels: style

#39 feat: forum fetch setup
  index.js
Labels: feature
