Repository jdwilkin4/fcc-forum-clone, pull requests merged in 2022-11, with the labels that each got.

#40 feat: display topic titles and categories
  helpers.js
  index.js
  styles.css
Labels: feature

#42 #[41]-double-slash-in-urls
  constants.js
Labels: bug

#47 chore: naming modifications
  index.js
Labels: chore

#49 feat: add forum user avatars
  constants.js
  index.html
  index.js
  styles.css
Labels: feature

#48 added recent activity time for each post and centered text for right 3 columns
  helpers.js
  index.js
  styles.css
Labels: feature

#53 feat: add forum replies #22
  index.js
Labels: feature
