Repository jdwilkin4/fcc-forum-clone, pull requests merged in 2022-09, with the labels that each got.

#16 Chore: added code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#17 docs: Added description to the README file
  README.md
Labels: documentation

#25 chore: Added URL constants
  constants.js
  index.js
Labels: chore

#15 Chore: add year to the footer
  index.html
  index.js
Labels: chore

#28 Chore: added-categories-obj
  helpers.js
  index.js
Labels: chore

#27 style: Added navbar
  images/fcc_primary_large.png
  index.html
  styles.css
Labels: style

#31 style: added bgcolor, font and h1
  index.html
  styles.css
Labels: style
